StartupEvents.registry('block', (event) => {
	event.create('rose_quartz_tile_stairs', 'stairs')
		.displayName('Rose Quartz Tile Stairs')
		.stoneSoundType()
		.tagBlock('mineable/pickaxe')
		.tagBlock("artifacts:mineable/digging_claws")
		.textureAll('create:block/palettes/rose_quartz_tiles');
	event.create('rose_quartz_tile_slab', 'slab')
		.displayName('Rose Quartz Tile Slab')
		.stoneSoundType()
		.tagBlock('mineable/pickaxe')
		.tagBlock('artifacts:mineable/digging_claws')
		.textureAll('create:block/palettes/rose_quartz_tiles');
	event.create('strawberry_crate', 'basic')
		.displayName('Strawberry Crate')
		.woodSoundType()
		.tagBlock('mineable/axe')
		.tagBlock('artifacts:mineable/digging_claws')
	event.create('sweet_strawberry_crate', 'basic')
		.displayName('Sweet Strawberry Crate')
		.woodSoundType()
		.tagBlock('mineable/axe')
		.tagBlock('artifacts:mineable/digging_claws')
	event.create('enchanted_berry_crate', 'basic')
		.displayName('Enchanted Berry Crate')
		.woodSoundType()
		.tagBlock('mineable/axe')
		.tagBlock('artifacts:mineable/digging_claws')
	event.create('enchanted_fruit_crate', 'basic')
		.displayName('Enchanted Fruit Crate')
		.woodSoundType()
		.tagBlock('mineable/axe')
		.tagBlock('artifacts:mineable/digging_claws')
	event.create('walnut_sack', 'basic')
		.displayName('Walnut Sack')
		.soundType('wool')
	event.create('prickly_pear_crate', 'basic')
		.displayName('Prickly Pear Crate')
		.woodSoundType()
		.tagBlock('mineable/axe')
		.tagBlock('artifacts:mineable/digging_claws')
	event.create('goldenleaf_berry_sack', 'basic')
		.displayName('Goldenleaf Berry Sack')
		.soundType('wool')
})