
[blocks]
	Kiln = true
	"Chiseled bricks" = true
	"Glazed terracotta" = true
	"Terracotta slabs, stairs, and walls" = false
	"Terracotta bricks" = true

	[blocks.decorated_pot]
		"Decorated pot colors" = false
		"Decorated pot trims" = true

