
#Flip settings
[Flip]
	#The chance of a flip happening when a mob falls from a high enough distance [0.0 = 0%, 0.1 = 10%, 1.0 = 100%] (Default: 0.35)
	#Range: 0.0 ~ 1.0
	flipChance = 1.0
	#When enabled turns the flippingMobs option into a blacklist [default: true]
	invertMobs = false
	#Defines a list of mobs that can flip when falling from a high enough distance [Format: modid:entity]
	flippingMobs = ["minecraft:cat", "minecraft:ocelot"]

