
["Homebound Configs"]
	#General
	#When you take damage while using a homebound item to teleport home the teleport is canceled and a cooldown is added before you can use it again.
	#This is to prevent players from easily teleporting out of a dangerous situation.
	#This value is how long of a cooldown in seconds is added when damage is taken. Set to 0 to disable taking damage from canceling the teleport
	#Range: > 0
	"Hurt Cooldown Time" = 5
	#How long it takes (in seconds) to bind your home to a location when you are crouching and using a homebound stone.
	#Range: > 0
	"Bind Home Use Duration" = 3
	#Slows the player by this amount when using a homebound stone. 1.0 means completely stopped, 0.0 means no slow applied.
	#Range: 0.0 ~ 0.7
	"Channel Slow Percentage" = 0.7
	#Homeward Item Cooldowns
	#All cooldowns are in minutes. All enchantments or cooldown reducing effects will apply to this base cooldown.
	#All use times are in seconds. This is the length of time it takes to activate the stone.
	#All max distances are in blocks. 16 blocks per chunk, so 160 blocks is 10 chunks. Having a value of 0 means no max distance.
	#Dimensional travel determines if the item can teleport you home from another dimension or not.
	#Blocks per bonus reduced means the number of blocks it takes to reduce the cooldown reduction effect by 1%. If this is set to 50 and the maximum distance reduction multiplier is 0.4 (or 40% cooldown reduction) and you are 51 blocks away from home, the cooldown reduction effect is now 0.39 (39%).
	#If this is set to 50 and the maximum distance reduction multiplier is 0.4 (or 40% cooldown reduction) and you are 51 blocks away from home, the cooldown reduction effect is now 0.39 (39%).
	#This will reduce by 1% for every 50 blocks away from home until the bonus is no longer applied at 0%. In the example above that would be 2000 blocks.
	#--- Homeward Bone ---
	#Range: > 0
	"Homeward Bone Cooldown" = 120
	#Range: > 0
	"Homeward Bone Use Time" = 15
	#Range: > 0
	"Homeward Bone Max Distance" = 0
	"Homeward Bone Dimensional travel allowed" = true
	#--- Hearthwood ---
	#Range: > 0
	"Hearthwood Cooldown" = 10
	#Range: > 0
	"Hearthwood Use Time" = 3
	#Range: > 0
	"Hearthwood Max Distance" = 160
	"Hearthwood Dimensional travel allowed" = false
	#--- Homeward Gem ---
	#Range: > 0
	"Homeward Gem Cooldown" = 60
	#Range: > 0
	"Homeward Gem Use Time" = 12
	#Range: > 0
	"Homeward Gem Max Distance" = 600
	"Homeward Gem Dimensional travel allowed" = false
	#--- Homeward Stone ---
	#Range: > 0
	"Homeward Stone Cooldown" = 60
	#Range: > 0
	"Homeward Stone Use Time" = 10
	#Range: > 0
	"Homeward Stone Max Distance" = 0
	"Homeward Stone Dimensional travel allowed" = false
	#--- Haven Stone ---
	#Range: > 0
	"Haven Stone Cooldown" = 60
	#Range: > 0
	"Haven Stone Use Time" = 10
	#Range: > 0
	"Haven Stone Max Distance" = 0
	"Haven Stone Dimensional travel allowed" = true
	#--- Dawn Stone ---
	#Range: > 0
	"Dawn Stone Cooldown" = 50
	#Range: > 0
	"Dawn Stone Use Time" = 9
	#Range: > 0
	"Dawn Stone Max Distance" = 0
	"Dawn Stone Dimensional travel allowed" = true
	#--- Sun Stone ---
	#Range: > 0
	"Sun Stone Cooldown" = 45
	#Range: > 0
	"Sun Stone Use Time" = 8
	#Range: > 0
	"Sun Stone Max Distance" = 0
	"Sun Stone Dimensional travel allowed" = true
	#--- Dusk Stone ---
	#Range: > 0
	"Dusk Stone Cooldown" = 60
	#Range: > 0
	"Dusk Stone Use Time" = 10
	#Range: > 0
	"Dusk Stone Max Distance" = 0
	"Dusk Stone Dimensional travel allowed" = true
	#Range: > 0
	"Dusk Stone Blocks Per Percent Reduced" = 40
	#Range: 0.0 ~ 1.0
	"Dusk Stone Maximum Distance Reduction Multiplier" = 0.6
	#--- Twilight Stone ---
	#Range: > 0
	"Twilight Stone Cooldown" = 60
	#Range: > 0
	"Twilight Stone Use Time" = 10
	#Range: > 0
	"Twilight Stone Max Distance" = 0
	"Twilight Stone Dimensional travel allowed" = true
	#Range: > 0
	"Twilight Stone Blocks Per Percent Reduced" = 40
	#Range: 0.0 ~ 1.0
	"Twilight Stone Maximum Distance Reduction Multiplier" = 0.7

