
#Puddles Settings
[Puddles]
	#How fast puddles generate - (0-5 is reasonable) Default: 5 - this is about 40 times as slow as snowfall
	#Range: 0 ~ 100
	puddleRate = 5
	#How fast puddles evaporate. Default: 50 - about twice as slow as snow/ice melting
	#Range: 0 ~ 100
	puddleEvaporationRate = 50
	#Allow splashing when jumping on puddles
	allowSplashing = true

